FROM node:23-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

FROM node:23-alpine AS runner

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/.next .next
COPY --from=builder /app/public public
COPY --from=builder /app/node_modules node_modules
COPY --from=builder /app/package.json package.json

EXPOSE 3000

CMD ["npm", "run", "start"]