name: Reuse Build Backend

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, edited, synchronize]
    branches: [master]
  workflow_dispatch:

jobs:
  use-shared-workflow:
    uses: nicholas-moniz/shared-pipeline/.github/workflows/build-nodejs.yaml@master
    with:
      library-path: ./shared-pipeline/.github/actions
